name: 'Pandora React App'
baseUrl: '/open'
development:
  host:
    - '^\/api\/test': 'http://localhost:9090'
    - '^\/api\/': '/'
  proxy:
    '/api/(.*)': 'http://test.pandolajs.com'
  localServerDomain: ''
test:
  host:
    - '^\/api\/': 'http://test.pandolajs.com'
preproduction:
  host:
    - '^\/api\/': 'http://pre.pandolajs.com'
production:
  host:
    - '^\/api\/': 'http://api.pandolajs.com'
